server:
  port: 8082
spring:
  application:
    #配置主机名
    name: client1
eureka:
  client:
    serviceUrl:
      #配置eureka服务发现主机的地址
      defaultZone: http://localhost:8081/eureka/

  instance:
    #将主机以ip地址形式注册在eureka中
    prefer-ip-address: true


#自定义配置
user:
  userServicePath: http://localhost:8081/getUser



#开启健康保护
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"